/**
 * Gallery photo dataset — plain data module (no "use client"). Imported by
 * the server page (galeria/page.tsx) so it can precompute blur placeholders
 * and aspect ratios per photo server-side, without the site-wide
 * blur-map.json (98KB) / image-dims.json (27KB) ending up in the client
 * bundle — GaleriaClient receives only the resolved per-photo values as
 * props (see EnrichedPhoto in GaleriaClient.tsx).
 */
export type Label = "Casamento" | "Corporativo" | "Conferência" | "Aéreo" | "Evento";

export interface PhotoSrc {
  src: string;
  label: Label;
}

export const PHOTOS: PhotoSrc[] = [
  { src: "/imagens/20_10_2025_0044.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0220.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0225.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0227.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0244.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0295.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0302.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0358.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0375.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0406.jpg", label: "Conferência" },
  { src: "/imagens/20_10_2025_0407.jpg", label: "Conferência" },
  { src: "/imagens/DaniGui_Adois_25.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Adois_27.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Adois_57.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Adois_58.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Adois_61.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Adois_66.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Adois_78.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_1.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_3.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_6.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_11.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_14.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_15.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_17.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_18.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_24.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_26.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_27.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_39.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_41.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_43.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_48.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_JantarFesta_130.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Preview12.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Preview18.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Preview19.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Preview20.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Preview70.jpg", label: "Casamento" },
  { src: "/imagens/DaniGui_Preview79.jpg", label: "Casamento" },
  { src: "/imagens/DJI_20250913190635_0120_D.jpg", label: "Aéreo" },
  { src: "/imagens/DJI_20250913190640_0121_D.jpg", label: "Aéreo" },
  { src: "/imagens/EW1_0362.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_0363.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_0365.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_0576.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_0580.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_0688.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_0689.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_0690.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_0697.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_0699.jpg", label: "Corporativo" },
  // NB: apesar do prefixo EW1 (maioritariamente corporativo), esta mostra os
  // noivos — verificado visualmente.
  { src: "/imagens/EW1_1100.jpg", label: "Casamento" },
  { src: "/imagens/EW1_1330.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1332.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1333.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1337.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1342.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1392.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1393.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1394.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1395.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1396.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1398.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1401.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1404.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1405.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1408.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1410.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1414.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1427.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1428.jpg", label: "Corporativo" },
  { src: "/imagens/EW1_1505.jpg", label: "Corporativo" },
  { src: "/imagens/ines-goncalo-157.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-242.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-250.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-251.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-252.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-253.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-278.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-282.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-346.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-421.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-498.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-499.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-502.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-506.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-509.jpg", label: "Casamento" },
  { src: "/imagens/ines-goncalo-510.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A1828.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A1933.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A1970.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A2021.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A2024.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A2025.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A2031.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A3489.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A3710.jpg", label: "Casamento" },
  { src: "/imagens/J&P-1Y1A3715.jpg", label: "Casamento" },
  { src: "/imagens/J&P-4B6A1405.jpg", label: "Casamento" },
  { src: "/imagens/J&P-4B6A1477.jpg", label: "Casamento" },
  { src: "/imagens/J&P-4B6A1492.jpg", label: "Casamento" },
  { src: "/imagens/J&P-4B6A1495.jpg", label: "Casamento" },
  { src: "/imagens/J&P-4B6A1506.jpg", label: "Casamento" },
  { src: "/imagens/J&P-DJI_20250628164714_0165_D.jpg", label: "Aéreo" },
  { src: "/imagens/J&P-DJI_20250628174247_0187_D.jpg", label: "Aéreo" },
  { src: "/imagens/J&P-DJI_20250628174304_0188_D.jpg", label: "Aéreo" },
  { src: "/imagens/J&P-IMGL2901.jpg", label: "Casamento" },
  { src: "/imagens/J&P-IMGL2906.jpg", label: "Casamento" },
  { src: "/imagens/J&P-IMGL3185.jpg", label: "Casamento" },
  { src: "/imagens/J&P-IMGL3186.jpg", label: "Casamento" },
  { src: "/imagens/J&P-IMGL3188.jpg", label: "Casamento" },
  { src: "/imagens/J&P-IMGL4767.jpg", label: "Casamento" },
  { src: "/imagens/J&P-IMGL4769.jpg", label: "Casamento" },
  { src: "/imagens/J&P-IMGL4770.jpg", label: "Casamento" },
  { src: "/imagens/J&P-IMGL5231.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3170.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3176.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3179.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3190.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3197.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3200.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3204.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3214.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3225.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3232.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3383.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3386.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3391.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3396.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3412.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3419.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3439.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3450.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A3453.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A4417.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A4430.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A4463.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A4467.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A4472.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A4738.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A5248.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A5254.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_1Y1A5263.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_DJI_20250628213855_0002_D.jpg", label: "Aéreo" },
  { src: "/imagens/JOAO_E_PEDRO_DJI_20250628213935_0005_D.jpg", label: "Aéreo" },
  { src: "/imagens/JOAO_E_PEDRO_IMGL1561.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_IMGL2180.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_IMGL2782.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_IMGL2825-2.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_IMGL4226.jpg", label: "Casamento" },
  { src: "/imagens/JOAO_E_PEDRO_IMGL5023.jpg", label: "Casamento" },
  { src: "/imagens/M&F0071.jpg", label: "Casamento" },
  { src: "/imagens/M&F0082.jpg", label: "Casamento" },
  { src: "/imagens/M&F0152.jpg", label: "Casamento" },
  { src: "/imagens/M&F0153.jpg", label: "Casamento" },
  { src: "/imagens/M&F0154.jpg", label: "Casamento" },
  { src: "/imagens/M&F0477.jpg", label: "Casamento" },
  { src: "/imagens/M&F0495.jpg", label: "Casamento" },
  { src: "/imagens/M&F0497.jpg", label: "Casamento" },
  { src: "/imagens/M&F0498.jpg", label: "Casamento" },
  { src: "/imagens/M&F0502.jpg", label: "Casamento" },
  { src: "/imagens/M&F0508.jpg", label: "Casamento" },
  { src: "/imagens/M&F0511.jpg", label: "Casamento" },
  { src: "/imagens/M&F0512.jpg", label: "Casamento" },
  { src: "/imagens/M&F0513.jpg", label: "Casamento" },
  { src: "/imagens/M&F0514.jpg", label: "Casamento" },
  { src: "/imagens/M&F0515.jpg", label: "Casamento" },
  { src: "/imagens/M&F0516.jpg", label: "Casamento" },
  { src: "/imagens/M&F0658.jpg", label: "Casamento" },
  { src: "/imagens/M&F0665.jpg", label: "Casamento" },
  { src: "/imagens/M&F0670.jpg", label: "Casamento" },
  { src: "/imagens/M&F0678.jpg", label: "Casamento" },
  { src: "/imagens/M&F0712.jpg", label: "Casamento" },
  { src: "/imagens/matilde-tomas-27.jpg", label: "Casamento" },
  { src: "/imagens/matilde-tomas-28.jpg", label: "Casamento" },
  { src: "/imagens/matilde-tomas-35.jpg", label: "Casamento" },
  { src: "/imagens/matilde-tomas-36.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-5.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-7.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-8.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-23.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-198.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-199.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-203.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-205.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-206.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-260.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-315.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-375.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-617.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-619.jpg", label: "Casamento" },
  { src: "/imagens/Natalia e Jonathan-620.jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-905.jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-907 (1).jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-908 (1).jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-909.jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-911 (1).jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-914 (1).jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-915 (1).jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-916 (1).jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-918.jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-923.jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-925.jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-1131.jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-1146.jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-1163.jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-1357 (1).jpg", label: "Casamento" },
  { src: "/imagens/teresinhaeze-1434.jpg", label: "Casamento" },
  { src: "/imagens/WhatsApp Image 2026-05-18 at 19.08.04.jpeg", label: "Casamento" },
  { src: "/imagens/WhatsApp Image 2026-05-18 at 19.08.04 (1).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-18 at 19.08.04 (2).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-18 at 19.08.04 (3).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-18 at 19.08.04 (4).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-18 at 19.08.04 (6).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-18 at 19.08.05.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-18 at 19.08.05 (1).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-18 at 19.08.05 (2).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.02.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.03.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.04.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.11.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.13.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.14.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.15.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.16.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.17.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.18.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.19.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.20.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.21.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.21 (1).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.22.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.22 (1).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.22 (2).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.22 (3).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.30.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.30 (1).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.30 (2).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.30 (3).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.31.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.33.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.33 (1).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.33 (2).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.34.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.34 (1).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.34 (2).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.35.jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.35 (1).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.35 (2).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.36.jpeg", label: "Casamento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.36 (1).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.36 (2).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.36 (3).jpeg", label: "Evento" },
  { src: "/imagens/WhatsApp Image 2026-05-21 at 11.53.37.jpeg", label: "Evento" },
  // ── Novas coleções (2026) ──
  { src: "/imagens/17860278387017661.jpg", label: "Evento" },
  { src: "/imagens/17920798061835097.jpg", label: "Evento" },
  { src: "/imagens/18002809616226216.jpg", label: "Evento" },
  { src: "/imagens/18009541247101258.jpg", label: "Evento" },
  { src: "/imagens/18030963605093473.jpg", label: "Evento" },
  { src: "/imagens/18299242414135399.jpg", label: "Evento" },
  { src: "/imagens/428658838-339551135742978-7904331374079927456-n.jpg", label: "Evento" },
  { src: "/imagens/428694133-339551105742981-427109035692944303-n.jpg", label: "Evento" },
  { src: "/imagens/428708341-339551125742979-6565889301500133407-n.jpg", label: "Evento" },
  { src: "/imagens/am20241026-miaejoao-1065.jpg", label: "Casamento" },
  { src: "/imagens/am20241026-miaejoao-1066.jpg", label: "Casamento" },
  { src: "/imagens/am20241026-miaejoao-1076.jpg", label: "Casamento" },
  { src: "/imagens/hd-edited.jpg", label: "Evento" },
  { src: "/imagens/image0.jpeg", label: "Evento" },
  { src: "/imagens/image2-1.jpeg", label: "Evento" },
  { src: "/imagens/image2.jpeg", label: "Evento" },
  { src: "/imagens/image4-1.jpeg", label: "Evento" },
  { src: "/imagens/image5-1.jpeg", label: "Evento" },
  { src: "/imagens/image6.jpeg", label: "Evento" },
  { src: "/imagens/image7.jpeg", label: "Evento" },
  { src: "/imagens/imagem-whatsapp-2025-08-18-as-23-01-39-4a836a89.jpg", label: "Evento" },
  { src: "/imagens/matilde-e-tomas0654-1.jpg", label: "Casamento" },
  { src: "/imagens/matilde-e-tomas0663.jpg", label: "Casamento" },
  { src: "/imagens/matilde-e-tomas0669.jpg", label: "Casamento" },
  { src: "/imagens/mom-0961.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-152.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-20.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-21.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-23.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-24.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-25.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-292.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-35.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-350.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-36.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-391.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-397.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-402.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-403.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-404.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-405.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-406.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-407.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-408.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-409.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-410.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-441.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-523.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-526.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-548.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-553-1.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-553.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-555-1.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-555.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-556.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-557.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-558.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-559.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-560.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-561-1.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-561.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-562.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-563.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-564.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-565.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-566.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-567.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-568.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-569.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-570.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-571-1.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-571.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-572.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-573.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-574.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-575.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-576.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-577.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-578.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-579.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-580.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-581.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-582.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-584.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-586.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-587.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-588.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-589.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-591.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-596.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-597.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-629.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-630.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-636.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-669.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-688.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-689.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-690.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-7.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-714.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-715.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-719.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-756.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-757.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-758.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-759.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-760.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-765.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-766.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-767.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-770.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-781.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-782.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-803.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-804.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-805.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-808.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-810.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-812-1.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-812.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-813.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-814.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-833.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-834-1.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-834.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-835.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-837.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-838-1.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-838.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-840.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-937.jpg", label: "Casamento" },
  { src: "/imagens/stephanie-mizio-940.jpg", label: "Casamento" },
  { src: "/imagens/J&A-8.jpg", label: "Casamento" },
  { src: "/imagens/J&A-9.jpg", label: "Casamento" },
  { src: "/imagens/J&A-10.jpg", label: "Casamento" },
  { src: "/imagens/J&A-51.jpg", label: "Casamento" },
  { src: "/imagens/J&A-52.jpg", label: "Casamento" },
  { src: "/imagens/J&A-59.jpg", label: "Casamento" },
  { src: "/imagens/J&A-67.jpg", label: "Casamento" },
  { src: "/imagens/J&A-68.jpg", label: "Casamento" },
  { src: "/imagens/J&A-69.jpg", label: "Casamento" },
  { src: "/imagens/J&A-73.jpg", label: "Casamento" },
  { src: "/imagens/J&A-76.jpg", label: "Casamento" },
  { src: "/imagens/J&A-206.jpg", label: "Casamento" },
  { src: "/imagens/J&A-207.jpg", label: "Casamento" },
  { src: "/imagens/J&A-216.jpg", label: "Casamento" },
  { src: "/imagens/J&A-218.jpg", label: "Casamento" },
  { src: "/imagens/J&A-219.jpg", label: "Casamento" },
  { src: "/imagens/J&A-225.jpg", label: "Casamento" },
  { src: "/imagens/J&A-242.jpg", label: "Casamento" },
  { src: "/imagens/J&A-243.jpg", label: "Casamento" },
  { src: "/imagens/J&A-272.jpg", label: "Casamento" },
  { src: "/imagens/J&A-338.jpg", label: "Casamento" },
  { src: "/imagens/J&A-339.jpg", label: "Casamento" },
  { src: "/imagens/J&A-342.jpg", label: "Casamento" },
  { src: "/imagens/J&A-351.jpg", label: "Casamento" },
  { src: "/imagens/J&A-368.jpg", label: "Casamento" },
  { src: "/imagens/J&A-369.jpg", label: "Casamento" },
  { src: "/imagens/J&A-370.jpg", label: "Casamento" },
  { src: "/imagens/J&A-371.jpg", label: "Casamento" },
  { src: "/imagens/J&A-372.jpg", label: "Casamento" },
  { src: "/imagens/J&A-377.jpg", label: "Casamento" },
  { src: "/imagens/J&A-387.jpg", label: "Casamento" },
  { src: "/imagens/J&A-394.jpg", label: "Casamento" },
  { src: "/imagens/J&A-421.jpg", label: "Casamento" },
  { src: "/imagens/J&A-427.jpg", label: "Casamento" },
  { src: "/imagens/J&A-442.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-122.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-123.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-128.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-129.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-130.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-133.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-573.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-574.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-575.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-576.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-577.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-578.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-579.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-580.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-582.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-583.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-584.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-585.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-586.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-587.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-588.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-593.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-594.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-595.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-596.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-598.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-599.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA-889.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-218.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-233.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-234.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-235.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-236.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-238.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-239.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-302.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-303.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-305.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-306.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-307.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-308.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-313.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-358.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-394.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-424.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-427.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-432.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-458.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-481.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-482.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-485.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-486.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-487.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-488.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-489.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-490.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-505.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-506.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-507.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-517.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-522.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-523.jpg", label: "Casamento" },
  { src: "/imagens/Sophia&Artur_MAINOVA_capa-524.jpg", label: "Casamento" },
];
